### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by AgustinPerez** [shwina/pyamgx#14]
Hello,

I've been trying to install _pyamgx_ unsuccessfully. The [instructions](https://pyamgx.readthedocs.io/en/latest/install.html#building-and-installing-pyamgx) at the website are clear and explicit and I think I've followed them correctly. 

1. I have AmgX running without issues. Examples included there are running perfectly.
2. Cython is available and operative (already checked at Spyder). The same happens with Scipy.
3. I'm working with Python 2.7 @ Spyder and the IPython console.
4. Environment variables are set up @ my bashrc.
> export AMGX_DIR=/home/user/Documents/AMGX-master

When I get to the step that requests: "_pip install ._" I get the following error message:

> user@cb2l-002:~/Documents/pyamgx$ pip install . --user
> /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
>   warnings.warn(warning, RequestsDependencyWarning)
> Processing /home/user/Documents/pyamgx
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-req-build-RQkQsR/setup.py", line 38
>         *AMGX_include_dirs
>         ^
>     SyntaxError: invalid syntax
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-RQkQsR/

I tried running setup.py from the IPython console to which I receive the very same output:

>   File "/home/user/Documents/pyamgx/setup.py", line 38
>     *AMGX_include_dirs
>     ^
> SyntaxError: invalid syntax

To my understanding the answer is simple. This is not accepted as it doesn't follow the Python syntaxis. This is unmodified code I just downloaded from here... maybe my Cython isn't properly running? maybe something got mixed up at the previous update of the code? 

I'd appreciate any input.
Thank you!

**Comment by shwina** [comment]
Thank you for reporting. This was an issue relating to Python 2 support in `setup.py`. Could you please try with the latest pyamgx?

**Comment by AgustinPerez** [comment]
It worked!

> Successfully built pyamgx
>Installing collected packages: pyamgx
>Successfully installed pyamgx-0.1

Thank you!
