### ISSUE TITLE
pyamgx.Matrix.replace_coefficients not working

### ISSUE THREAD

**Issue by qingshanchen** [shwina/pyamgx#15]
Hi,

It appears that pyamgx.Matrix.replace_coefficients is not working properly. The AMGX documentation says that for this function to work, matrix_upload_all must have been called previously. This function is not yet available in PYAMGX, and this may be the reason?

**Comment by shwina** [comment]
@qingshanchen Are you still running into this? If so, could you please provide a failing example?

**Comment by shwina** [comment]
@qingshanchen May this issue be closed?

**Comment by shwina** [comment]
Closing issue but please feel free to reopen
