### ISSUE TITLE
build in windows

### ISSUE THREAD

**Issue by pyramidpoint** [shwina/pyamgx#16]
warning: I don't know what to do with 'runtime_library_dirs': ['C:\\Users\\Administrator\\Anaconda3\\lib\\site-packages\\numpy\\core\\include', 'C:\\ProgramData\\NVIDIA Corporation\\AMGX-master\\build']
    error: don't know how to set runtime library search path for MSVC

**Comment by ercanburak** [comment]
@pyramidpoint I also get the same error while trying to install on a Windows machine. Did you find a way to fix this and successfully perform the installation on Windows?
