### ISSUE TITLE
upload_raw for matrices?

### ISSUE THREAD

**Issue by qingshanchen** [shwina/pyamgx#20]
Hi,
I will be very happy to see an upload_raw method for matrices, just like the method with the same name for vectors. This method will allow us to upload the matrix with data already on the GPU, which can potentially reduce the time spent for data transferring. Thanks!
--qingshan

**Comment by shwina** [comment]
@qingshanchen It should now be possible to use `Matrix.upload()` with both numpy as well as CuPy arrays, and any other objects that expose [`__array_interface__`](https://numpy.org/doc/stable/reference/arrays.interface.html) or [`__cuda_array_interface__`](https://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html). Please let me know if this works for you.

**Comment by shwina** [comment]
Closing as this is resolved. Thanks!
