### ISSUE TITLE
upload_CSR( ) is not calling upload( ) correctly?

### ISSUE THREAD

**Issue by qingshanchen** [shwina/pyamgx#3]
pyamgx/Matrix.pyx in pyamgx.Matrix.upload_CSR (pyamgx/pyamgx.c:3191)()

pyamgx/Matrix.pyx in pyamgx.Matrix.upload (pyamgx/pyamgx.c:2830)()

TypeError: upload() takes at most 4 positional arguments (5 given)

**Comment by shwina** [comment]
Thanks. Fixed by be54232.
