### ISSUE TITLE
build

### ISSUE THREAD

**Issue by peteryim** [shwina/pyamgx#6]
I tried to build pyamgx but I got an error - see below.  AMGX was properly installed and AMGX_DIR environment variable was set to the root directory of AMGX (in my case /home/pyim/AMGX_master).

Any ideas?

python setup.py build_ext
running build_ext
building 'pyamgx' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/numpy/core/include -I/public/apps/python/2.7.12/gcc.6.2.0/include/python2.7 -c pyamgx/pyamgx.c -o build/temp.linux-x86_64-2.7/pyamgx/pyamgx.o
pyamgx/pyamgx.c:9:20: warning: "/*" within comment [-Wcomment]
             "pyamgx/*.pyx, pyamgx/*.pxi"

pyamgx/pyamgx.c:9:34: warning: "/*" within comment [-Wcomment]
pyamgx/pyamgx.c:506:20: fatal error: amgx_c.h: No such file or directory
 #include "amgx_c.h"
                    ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by shwina** [comment]
Sorry for the incomplete instructions. I'll update as soon as I get a chance. Could you try the following?

```
export AMGX_DIR=/home/atrikut/local/AMGX
export C_INCLUDE_PATH=$AMGX_DIR/base/include:$C_INCLUDE_PATH
export C_INCLUDE_PATH=$AMGX_DIR/core/include:$C_INCLUDE_PATH
export LD_LIBRARY_PATH=$AMGX_DIR/build:$LD_LIBRARY_PATH
export CPLUS_INCLUDE_PATH=$C_INCLUDE_PATH
export LIBRARY_PATH=$LD_LIBRARY_PATH
```

**Comment by peteryim** [comment]
I set those variables but got the same error though.  

I checked the $C_INCLUDE_PATH variable - it doesn't look right:

echo $C_INCLUDE_PATH
/base/include:/home/pyim/AMGX-master/buildpyim/AMGX-master/base/include:/home/pyim/AMGX-master

**Comment by shwina** [comment]
Thanks. The `C_INCLUDE_PATH` variable is a colon separated list of directories where the compiler searches for header files. Specifically, you should make sure that `$AMGX_DIR/base/include` and `$AMGX_DIR/core/include` are in this list.

Something definitely looks amiss as I see `/home/pyim/AMGX-master/build` as part of the `C_INCLUDE_PATH`.

Could you try again exactly the following commands:

```
export AMGX_DIR=/home/pyim/AMGX_master
export C_INCLUDE_PATH=$AMGX_DIR/base/include:$C_INCLUDE_PATH
export C_INCLUDE_PATH=$AMGX_DIR/core/include:$C_INCLUDE_PATH
export LD_LIBRARY_PATH=$AMGX_DIR/build:$LD_LIBRARY_PATH
export CPLUS_INCLUDE_PATH=$C_INCLUDE_PATH
export LIBRARY_PATH=$LD_LIBRARY_PATH
```

and if it doesn't work, could you show me the values of the above variables?

**Comment by peteryim** [comment]
Still same error.  Values of each of the environment variables are below:

echo $AMGX_DIR
/home/pyim/AMGX-master

echo $C_INCLUDE_PATH
/base/include:/home/pyim/AMGX-master

echo $LD_LIBRARY_PATH
/public/apps/atlas/3.11.38/gcc.6.2.0/lib:/public/apps/fftw/3.3.4/gcc.6.2.0/lib:/public/apps/bzip2/1.0.6/lib:/public/apps/openssl/1.0.2g/gcc.6.2.0/lib:/public/apps/zlib/1.2.8/gcc.6.2.0/lib:/public/apps/binutils/2.27/gcc.6.2.0/lib:/public/apps/gcc/6.2.0/lib64:/public/apps/p/build:/public/apps/cuda/8.0/lib64yim/AMGX-master

echo $CPLUS_INCLUDE_PATH
/base/include:/home/pyim/AMGX-master

echo $LIBRARY_PATH
/build:/public/apps/binutils/2.25.1/gcc.4.9.0/lib:/public/apps/zlib/1.2.8/gcc.4.9.0/lib:/public/apps/gcc/4.9.0/lib64:/public/apps/cuda/8.0/lib64

**Comment by peteryim** [comment]
That seems to be OK now - I just used "/home/peter/AMGX-master" instead of "$AMGX_DIR".    I am now running into a permissions issue on the  "pip install . --user"

**Comment by shwina** [comment]
What error are you getting?

**Comment by peteryim** [comment]
See below:

pip install . --user
Traceback (most recent call last):
  File "/public/apps/python/2.7.12/gcc.6.2.0/bin/pip", line 7, in <module>
    from pip import main
  File "/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3031, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 651, in _build_master
    ws = cls()
  File "/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2017, in find_on_path
    if len(os.listdir(fullpath)) == 0:
OSError: [Errno 13] Permission denied: '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/Werkzeug-0.12.2.dist-info'

**Comment by shwina** [comment]
Hmm. Sorry, I don't know immediately how to fix this. Of course you could try:

```
$ sudo pip install .
```

Could you describe your setup a bit more? What operating system is this, and how was Python installed?

As an aside, I'm not sure if `pyamgx` is compatible with Python 2.x.

**Comment by peteryim** [comment]
I don't have privileges to modify the system-wide Python library but I do have full access/control over my account directories etc.  It is CENTOS operating system.  "sudo pip install ." didn't work - I don't have the password.

**Comment by shwina** [comment]
`pip install . --user` typically installs packages to your home directory. Could you try the following commands in a Python prompt and report the output:

```
>>> import site
>>> site.USER_BASE
```

`site.USER_BASE` tells you where `pip` will install packages when used with the `--user` switch. If this is *not* somewhere in your home directory, it's probably best to speak to your system administrator to ask how they expect you to install Python packages for yourself.

**Comment by peteryim** [comment]
site.USER_BASE is  "/home/peter/.local"  .  I created that directory and tried rerunning "pip install  . --user" but got the same error.

I did try to install another python package - "python-package-example" and I got the same error - so it is probably not a pyamgx issue.

**Comment by shwina** [comment]
Could you also report the value of `sys.path`?

```
>>> import sys
>>> print(sys.path)
```

One way around the issue you are facing right now:

1. Specify `/home/$USER/.local` as the install prefix while installing:

```
$ pip install --prefix=/home/$USER/.local .
```

(here `$USER` is your username)

2. Before running Python, modify your `PYTHONPATH`:

```
export PYTHONPATH=$PYTHONPATH:/home/$USER/.local/lib/python2.7/site-packages
```

**Comment by peteryim** [comment]
Same problem - also sys.path is below.   

>>> import sys
>>> print (sys.path)
['', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/gdc_client-1.2.0-py2.7.egg', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/setuptools-19.2-py2.7.egg', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/PyYAML-3.11-py2.7-linux-x86_64.egg', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/gdc_client-1.2.0-py2.7.egg', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/jsonschema-2.5.1-py2.7.egg', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/setuptools-19.2-py2.7.egg', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/PyYAML-3.11-py2.7-linux-x86_64.egg', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/pandas-0.22.0-py2.7-linux-x86_64.egg', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages/Theano-1.0.1-py2.7.egg', '/public/apps/cython/0.24.1/python.2.7.12/gcc.6.2.0/lib/python2.7/site-packages', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/site-packages', '/public/apps/numpy/1.11.1/python.2.7.12/gcc.6.2.0/lib/python2.7/site-packages', '/public/apps/scipy/0.18.1/python.2.7.12/gcc.6.2.0/lib/python2.7/site-packages', '/home/peter/.local/lib/python2.7/site-packages\r', '/home/peter/.local/lib/python2.7.12/site-packages\r', '/public/apps/cython/0.24.1/python.2.7.12/gcc.6.2.0/lib/python2.7/site-packages/Cython-0.24.1-py2.7-linux-x86_64.egg', '/public/apps/numpy/1.11.1/python.2.7.12/gcc.6.2.0/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg', '/public/apps/scipy/0.18.1/python.2.7.12/gcc.6.2.0/lib/python2.7/site-packages/scipy-0.18.1-py2.7-linux-x86_64.egg', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python27.zip', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/plat-linux2', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/lib-tk', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/lib-old', '/public/apps/python/2.7.12/gcc.6.2.0/lib/python2.7/lib-dynload', '/home/peter/.local/lib/python2.7/site-packages\r', '/home/peter/.local/lib/python2.7/site-packages\r', '/home/peter/.local/lib/python2.7.12/site-packages\r', '/home/peter/.local/lib/python2.7/site-packages\r']

**Comment by peteryim** [comment]
One complicating factor - I may need to ask the system administrator about - is that in order to run Python on this system - Penguin Computing Pod - I need to "load"  the Python "module".  That has the effect of changing path variables.   I noticed that when I change the PYTHONPATH variable - the command "python" doesn't work.

**Comment by shwina** [comment]
Thanks. Yes, I'm really all out of ideas other than to talk to your sysadmin, as it's not clear to me how this Python module is configured.

One final suggestion I have would be for you to install your own Python in your home directory, rather than using the Python module on your system. I highly recommend Anaconda as it's fairly easy to install and comes with the most popular packages like NumPy, SciPy preinstalled:

https://www.anaconda.com/download/

Once you have that setup, you can try the install instructions for `pyamgx` again.

**Comment by peteryim** [comment]
It does install with Anaconda.  The test program demo.py did not complete - see below.

$ python demo.py
AMGX version 2.0.0.130-opensource
Built on Apr 15 2018, 00:16:31
Compiled with CUDA Runtime 8.0, using CUDA driver 8.0
/core/configs/FGMRES_AGGREGATION.json'ster
/core/configs/FGMRES_AGGREGATION.json'ster
/core/configs/FGMRES_AGGREGATION.jsonyim/AMGX-master
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    cfg = pyamgx.Config().create_from_file(os.environ['AMGX_DIR']+'/core/configs/FGMRES_AGGREGATION.json')
  File "pyamgx/Config.pyx", line 46, in pyamgx.Config.create_from_file
    check_error(AMGX_config_create_from_file(&self.cfg, param_file))
  File "pyamgx/Errors.pyx", line 62, in pyamgx.check_error
    raise AMGXError(get_error_string(err_code))
pyamgx.AMGXError: Incorrect amgx configuration provided.
[pyim@n230 pyamgx-master]$

**Comment by shwina** [comment]
Thanks - make sure to set `AMGX_DIR` before running the example.

**Comment by peteryim** [comment]
Yes - it works!   

It did require slight change to demo.py - the variable $AMGX_DIR was set but did not seem to be recognized by demo.py - I just replaced with actual path.

**Comment by shwina** [comment]
Great! Thanks for letting me know.

I'm not sure why these issues with environment variables are coming up. Just to confirm, are you using `export` while setting the values of environment variables?

I'm closing this issue for now, but please don't hesitate to open new ones with any further feedback.

**Comment by yash-goel** [comment]
Hi, I am facing the same error with pyamgx install. AMGX is properly installed which I checked by running the given example. Further I am using anaconda environment. I did also set the environment variable for `AMGX_DIR`.

`echo $AMGX_DIR` gives the correct path.

Still I end with the same error on running `pip install .` :

`Processing /home/yash/nvidia_amgx/pyamgx
Building wheels for collected packages: pyamgx
  Building wheel for pyamgx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/yash/anaconda3/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0vss0fu4/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0vss0fu4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-c1e3ewww
       cwd: /tmp/pip-req-build-0vss0fu4/
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'pyamgx' extension
  creating build
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/pyamgx
  gcc -pthread -B /home/yash/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yash/.local/lib/python3.8/site-packages/numpy/core/include -I/home/yash/nvidia_agmx/AGMX/base/include -I/home/yash/nvidia_agmx/AGMX/core/include -I/home/yash/anaconda3/include/python3.8 -c pyamgx/pyamgx.c -o build/temp.linux-x86_64-3.8/pyamgx/pyamgx.o
  pyamgx/pyamgx.c:9:20: warning: "/*" within comment [-Wcomment]
               "pyamgx/*.pyx, pyamgx/*.pxi"
  
  pyamgx/pyamgx.c:9:34: warning: "/*" within comment [-Wcomment]
  pyamgx/pyamgx.c:642:10: fatal error: amgx_c.h: No such file or directory
   #include "amgx_c.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyamgx
`

Thanks for the help in advance!

**Comment by shwina** [comment]
Thanks for reporting! What's the output of the following?

```
ls $AMGX_DIR
```

**Comment by yash-goel** [comment]
You saw right through it, I just noticed back. The error even mentions it. I mixed the letters in the path. Sorry for the inconvenience. It is all good now! Thanks again :)

**Comment by shwina** [comment]
No worries! Closing this issue again
